version: 2
jobs:
  test:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: Pip dependencies
          command: sudo pip install black nbformat click codecov coverage
      - run:
          name: Installation
          command: sudo python setup.py install
      - run:
          name: Installation
          command: coverage run tests/example_test.py
      - run:
          name: CodeCov
          command: codecov --token=$codecov
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
