version: 2
jobs:
  test:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: Pip dependencies
          command: sudo pip install tox codecov pytest pytest-cov
      - run:
          name: Installation
          command: sudo python setup.py install
      - run:
          name: Tests
          command: tox
      - run:
          name: CoverageUpload
          command: codecov --token=$codecov
workflows:
  version: 2
  build_and_test:
    jobs:
      - test