version: 2
jobs:
  formatting:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Pip dependencies
          command: sudo pip install nox
      - run:
          name: Formatting
          command: sudo nox
workflows:
  version: 2
  build_and_test:
    jobs:
      - formatting