version: 2
jobs:
  formatting:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Pip dependencies
          command: pip install --user nox
      - run:
          name: Formatting
          command: /home/circleci/.local/bin/nox
workflows:
  version: 2
  build_and_test:
    jobs:
      - formatting