version: 2
jobs:
  build:
    docker:
      - image: circleci/python:
    steps:
      - checkout
      - run:
          name: Pip dependencies
          command: pip install --quiet black nbformat click
  test:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: Pip dependencies
          command: pip install --quiet black nbformat click
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
