version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: Pip dependencies
          command: pip install --user --quiet black nbformat click
      - run:
          name: Installation
          command: python setup.py install --user
  test:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: Pip dependencies
          command: pip install --user --quiet black nbformat click
      - run:
          name: Installation
          command: python setup.py install --user
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
