version: 2
jobs:
  formatting:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: Pip dependencies
          command: sudo pip install nox codecov pytest pytest-cov flake8 pylint isort jsonschema
      - run:
          name: Formatting
          command: sudo nox
  test:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: Pip dependencies
          command: sudo pip install codecov pytest pytest-cov poetry
      - run:
          name: Installation
          command: sudo poetry install
      - run:
          name: Tests
          command: pytest --cov=./ && codecov --token=$CODECOV_TOKEN
workflows:
  version: 2
  build_and_test:
    jobs:
      - formatting
      - test:
          requires:
            - formatting